# Oh My Zsh 配置文件 - 极致优化版
export ZSH="$HOME/.oh-my-zsh"

# 主题与别名
ZSH_THEME="robbyrussell"

# 插件列表 (根据 Dockerfile 加载对应插件)
plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
    zsh-completions
)

source $ZSH/oh-my-zsh.sh

# 语言与字符集补全
export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8

# 高性能别名
alias hx='hexo'
alias hxc='hexo clean && hexo g'
alias hxs='hexo s'
alias p2='pm2'
alias p2l='pm2 logs'

# 提示词优化
PROMPT='%F{cyan}%n%f@%F{orange}%m%f %F{blue}%~%f %# '
